<a href="https://colab.research.google.com/github/NhatHuy2k2/AI/blob/main/Week8_ANN_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.linear_model import Perceptron
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import numpy as np
# sklearn: thư viện cho machine learning, deep learning, ANN, ...

Training an iris recognition model



In [83]:
iris = datasets.load_iris()
#print(iris)


In [84]:
x = iris.data
y = iris.target
print(x[:5])
print(y[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [85]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)
sc = StandardScaler()
sc.fit(x_train)
x_train_std = sc.transform(x_train)
x_test_std = sc.transform(x_test)

print(x_train_std[:5])

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)


[[-0.39119315 -1.82334276  0.19330193  0.15854007]
 [-1.39302926  0.31444745 -1.19450678 -1.28330075]
 [-1.01734072  1.26457643 -1.3101575  -1.28330075]
 [-1.14257023  0.0769152  -1.25233214 -1.28330075]
 [-0.01550461 -1.11074602  0.19330193  0.02746363]]
(105, 4)
(45, 4)
(105,)
(45,)


In [86]:
model = Perceptron(max_iter = 100, eta0 = 0.1, random_state = 0)
#model: số lần học
#eta: tốc độ học, có giá trị từ (0,1), tốc độ càng nhỏ càng chính xác*
model.fit(x_train_std, y_train)
y_pred = model.predict(x_test_std)
print(y_pred)
print(y_test)
print("Độ chính xác của mô hình: ", accuracy_score(y_test, y_pred))

[0 1 1 1 1 2 1 1 1 1 1 0 1 0 0 2 1 1 0 1 1 0 0 1 1 1 0 2 1 0 1 2 0 1 2 0 1
 0 1 2 0 1 2 1 1]
[0 1 2 1 1 2 2 1 2 1 2 0 2 0 0 2 1 2 0 2 2 0 0 1 1 1 0 2 1 0 1 2 0 1 2 0 1
 0 2 2 0 2 2 2 1]
Độ chính xác của mô hình:  0.7555555555555555
